// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBf5TbjfPzX8MPsGgzpwn8rQWSYLzS9v0I',
    appId: '1:691428933196:web:c5bc9cf735b93261bd7ee9',
    messagingSenderId: '691428933196',
    projectId: 'app-hora-extra',
    authDomain: 'app-hora-extra.firebaseapp.com',
    storageBucket: 'app-hora-extra.firebasestorage.app',
    measurementId: 'G-WHHJWMN0P2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqXP_TXSueI4J1194dYfFMZjVhWEemozg',
    appId: '1:691428933196:android:0aac9a85b95e25e8bd7ee9',
    messagingSenderId: '691428933196',
    projectId: 'app-hora-extra',
    storageBucket: 'app-hora-extra.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAntt2v5zzZrvMdilsZqUO7z6GGEoji3NE',
    appId: '1:691428933196:ios:800c15ebf1c855c4bd7ee9',
    messagingSenderId: '691428933196',
    projectId: 'app-hora-extra',
    storageBucket: 'app-hora-extra.firebasestorage.app',
    iosBundleId: 'com.example.senior',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAntt2v5zzZrvMdilsZqUO7z6GGEoji3NE',
    appId: '1:691428933196:ios:800c15ebf1c855c4bd7ee9',
    messagingSenderId: '691428933196',
    projectId: 'app-hora-extra',
    storageBucket: 'app-hora-extra.firebasestorage.app',
    iosBundleId: 'com.example.senior',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBf5TbjfPzX8MPsGgzpwn8rQWSYLzS9v0I',
    appId: '1:691428933196:web:2d5abf85db2367eebd7ee9',
    messagingSenderId: '691428933196',
    projectId: 'app-hora-extra',
    authDomain: 'app-hora-extra.firebaseapp.com',
    storageBucket: 'app-hora-extra.firebasestorage.app',
    measurementId: 'G-WCPHY39C8Z',
  );
}
